server:
  port: 8011
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  client:
#    service-url: http://${eureka.instance.hostname}:${server.port}/eureka/