server:
  port: 8012

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka

spring:
  application:
    name: zcb-cloud-provider
  zipkin:
    base-url: http://localhost:8015/
  sleuth:
    sampler:
      percentage: 1.0

app:
  id: zcb-cloud-provider

apollo:
  meta: http://localhost:8080

