
server:
  port: 8013
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka
spring:
  application:
    name: zcb-cloud-consumer
  zipkin:
    base-url: http://localhost:8015/
  sleuth:
    sampler:
      percentage: 1.0

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

